CREATE TABLE IF NOT EXISTS users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        VARCHAR(40)  NOT NULL,
    name       VARCHAR(256) NOT NULL,
    login      VARCHAR(256) NOT NULL,
    password   VARCHAR(256) NOT NULL,
    created_at DATE         NOT NULL,
    updated_at DATE         NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_uids ON users (uid);
CREATE UNIQUE INDEX IF NOT EXISTS users_logins ON users (login);

CREATE TABLE IF NOT EXISTS contacts
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        VARCHAR(40)  NOT NULL,
    first_name VARCHAR(256) NOT NULL,
    last_name  VARCHAR(256) NOT NULL,
    user_id    VARCHAR(40)  NOT NULL,
    created_at DATE         NOT NULL,
    updated_at DATE         NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS contacts_uids ON contacts (uid);


CREATE TABLE IF NOT EXISTS emails
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER      NOT NULL,
    email      VARCHAR(256) NOT NULL,
    created_at DATE         NOT NULL,
    updated_at DATE         NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS phone_numbers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id   INTEGER      NOT NULL,
    phone_number VARCHAR(256) NOT NULL,
    created_at   DATE         NOT NULL,
    updated_at   DATE         NOT NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts (id)
);